const getEnv = (): Record<string, string> => {
  return {
    NEXT_PUBLIC_AUTH0_PEAKO_DOMAIN: process.env.NEXT_PUBLIC_AUTH0_PEAKO_DOMAIN ?? '',
    NEXT_PUBLIC_AUTH0_PEAKO_CLIENT_ID: process.env.NEXT_PUBLIC_AUTH0_PEAKO_CLIENT_ID ?? '',
    NEXT_PUBLIC_AUTH0_PEAKO_AUDIENCE: process.env.NEXT_PUBLIC_AUTH0_PEAKO_AUDIENCE ?? '',
    NEXT_PUBLIC_AUTH0_VITA_AUDIENCE: process.env.NEXT_PUBLIC_AUTH0_VITA_AUDIENCE ?? '',
    NEXT_PUBLIC_AUTH0_VITA_CLIENT_ID: process.env.NEXT_PUBLIC_AUTH0_VITA_CLIENT_ID ?? '',
    NEXT_PUBLIC_AUTH0_VITA_DOMAIN: process.env.NEXT_PUBLIC_AUTH0_VITA_DOMAIN ?? '',
  };
};

export default getEnv;